{{- if .Values.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: vc-webhook-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCert | default "" | quote }}
  tls.key: {{ .Values.tlsKey | default "" | quote }}
{{- end }}
